# Generated by Django 4.1.9 on 2024-03-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100)),
                ('Course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.course_title')),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.session')),
            ],
        ),
    ]
