# Generated by Django 4.1.9 on 2024-03-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='need_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(default='hall', max_length=250)),
                ('borrower_name', models.CharField(max_length=250)),
                ('writer_name', models.CharField(max_length=250)),
                ('roll', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
                ('Course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.course_title')),
            ],
        ),
        migrations.CreateModel(
            name='available_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=250)),
                ('owner_name', models.CharField(max_length=250)),
                ('writer_name', models.CharField(max_length=250)),
                ('roll', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
                ('Course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.course_title')),
            ],
        ),
    ]
