# Generated by Django 4.1.9 on 2023-07-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='available_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=250)),
                ('owner_name', models.CharField(max_length=250)),
                ('writer_name', models.CharField(max_length=250)),
                ('roll', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='course_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='need_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(default='hall', max_length=250)),
                ('borrower_name', models.CharField(max_length=250)),
                ('writer_name', models.CharField(max_length=250)),
                ('roll', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
                ('Course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.course_title')),
            ],
        ),
        migrations.CreateModel(
            name='beg_for_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.available_books')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='available_books',
            name='Course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.course_title'),
        ),
    ]
