# Generated by Django 4.1.9 on 2023-06-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='available_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(max_length=250)),
                ('books_name', models.CharField(max_length=250)),
                ('owner_name', models.CharField(max_length=250)),
                ('writer_name', models.CharField(max_length=250)),
                ('roll', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='need_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(default='cse', max_length=250)),
                ('books_name', models.CharField(default='hall', max_length=250)),
                ('borrower_name', models.CharField(max_length=250)),
                ('writer_name', models.CharField(max_length=250)),
                ('roll', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
            ],
        ),
    ]
