# Generated by Django 4.1.9 on 2024-03-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='beg_for_book',
        ),
    ]
